# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# THEME REDEFINE CONFIGURATION FILE V2
# BY EVANNOTFOUND
# GITHUB: https://github.com/EvanNotFound/hexo-theme-redefine
# DOCUMENTATION: https://redefine-docs.ohevan.com
# DEMO: https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# BASIC INFORMATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
info:
  title: Zero and One
  author: Zero6992
  url: https://zero6992.me/
# BASIC INFORMATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# IMAGE CONFIGURATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
defaults:
  favicon: https://user-images.githubusercontent.com/89479282/230354320-72b60ed2-6abf-479a-8676-ac427c676503.png
  logo: 
  avatar: https://user-images.githubusercontent.com/89479282/230348631-4222d9cc-3700-4b53-ac9c-500627e19569.jpeg
# IMAGE CONFIGURATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# COLORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
colors:
  primary: "#30b067"
  secondary: 
  default_mode: light
# COLORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# SITE CUSTOMIZATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
global:
  fonts:
    chinese:
      enable: true
      family: Noto Serif TC
      url: https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@600&display=swap
    english:
      enable: false
      family: 
      url: 
  content_max_width: 1500px
  sidebar_width: 210px
  hover:
    shadow: true
    scale: false
  scroll_progress:
    bar: false
    percentage: true
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true
    site_uv: true
    post_pv: true
  single_page: true
  preloader: true
  open_graph: true
  google_analytics:
    enable: true
    id: G-FLZZCT89LL
# SITE CUSTOMIZATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# FONTAWESOME >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
fontawesome:
  thin: false
  light: false
  duotone: false
  sharp_solid: false
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# HOME BANNER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home_banner:
  enable: true
  style: fixed
  image:
    light: /images/wallhaven-wqery6-light.webp
    dark: /images/wallhaven-wqery6-dark.webp
  title: Zero6992
  subtitle:
    text: [
    "Those who don't learn from the past, are destined to repeat it.",
    "那些不能從歷史中吸取教訓的人注定要重蹈覆轍。",
    "過去の失敗をすぐ忘れてしまい教訓にできない人は、必ず同じ失敗を繰り返す運命にある。",
    ]
    hitokoto:
      enable: false
      api: https://v1.hitokoto.cn
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
    smart_backspace: true
  text_color:
    light: "#fff"
    dark: "#d1d1b6"
  text_style:
    title_size: 2.8rem
    subtitle_size: 1.5rem
    line_height: 1.2
  custom_font:
    enable: true
    family: Noto Serif TC
    url: https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@500;900&family=Noto+Serif+TC:wght@500&family=Roboto+Mono:wght@600&display=swap
  social_links:
    enable: true
    style: default
    links:
      github: https://github.com/Zero6992
      linkedin: https://www.linkedin.com/in/zero6992
      twitter: https://twitter.com/ha1fu
      email: zero69992@gmail.com
    qrs: 
# HOME BANNER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# NAVIGATION BAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
navbar:
  auto_hide: true
  color:
    left: "#f78736"
    right: "#367df7"
    transparency: 35
  width:
    home: 1200px
    pages: 1000px
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Github:
      path: https://github.com/Zero6992
      icon: fa-brands fa-github
    About:
      path: /about
      icon: fa-regular fa-user
  search:
    enable: false
    preload: true
# NAVIGATION BAR <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# HOME PAGE ARTICLE SETTINGS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home:
  sidebar:
    enable: true
    position: left
    first_item: menu
    announcement:
    show_on_mobile: true
    links: {}
  article_date_format: auto
  categories:
    enable: true
    limit: 3
  tags:
    enable: true
    limit: 3
# HOME PAGE ARTICLE SETTINGS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# ARTICLE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
articles:
  style:
    font_size: 16px
    line_height: 1.8
    image_border_radius: 14px
    image_alignment: center
    image_caption: false
    link_icon: true
    title_alignment: left
    headings_top_spacing:
      h1: 5rem
      h2: 4rem
      h3: 2.8rem
      h4: 2.5rem
      h5: 2.2rem
      h6: 2rem
  word_count:
    enable: true
    count: true
    min2read: true
  author_label:
    enable: true
    auto: false
    list: []
  code_block:
    copy: true
    style: mac
    font:
      enable: true
      family: Noto Serif TC
      url: https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@600&display=swap
  toc:
    enable: true
    max_depth: 3
    number: false
    expand: true
    init_open: true
  copyright:
    enable: true
    default: cc_by_nc_sa
  lazyload: true
  recommendation:
    enable: false
    title: recommendation
    limit: 3
    mobile_limit: 2
    placeholder: /images/wallhaven-wqery6-light.webp
    skip_dirs: []
# ARTICLE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# COMMENT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
comment:
  enable: true
  system: waline
  config:
    waline:
      serverUrl: https://example.example.com
      lang: en-US
      emoji: []
      recaptchaV3Key: wasd
    gitalk: {}
    twikoo: {}
    giscus: {}
# COMMENT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# FOOTER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
footer:
  runtime: true
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  start: 2023/04/01 04:20:00
  statistics: true
  customize: {}
  icp: {}
# FOOTER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# INJECT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
inject:
  enable: false
  head: []
  footer: []
# INJECT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# PLUGINS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
plugins:
  feed:
    enable: false
  aplayer: {}
  mermaid:
    enable: false
    version: "9.3.0"
# PLUGINS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# PAGE TEMPLATES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
page_templates:
  friends_column: 2
  tags_style: blur
# PAGE TEMPLATES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
cdn:
  enable: false
  provider: unpkg
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# DEVELOPER MODE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
developer:
  enable: false
# DEVELOPER MODE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
